language: php
php:
- '7.4.0'
- '7.4.2'
before_install:
- travis_retry composer self-update
- cp .env.example .env
install:
- composer install --no-interaction --prefer-source
script:
- php vendor/bin/phpunit
- php vendor/bin/psalm
